import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/headers/NavBar";
import Footer from "@/components/footer/Footer";
import Session from "./Session";
import ProviderStore from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderStore>
        <Session>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <NavBar />
            <main className="mb-10 min-h-[100vh]">{children}</main>
            <Footer />
          </body>
        </Session>
      </ProviderStore>
    </html>
  );
}
